### ISSUE TITLE
pdfminer can't parse characters outside the ASCII encoding

### ISSUE THREAD

**Issue by marianorodriguez** [axa-group/Parsr#136]
Attached is a document in spanish that shows that pdfminer cant process latin characters like:
á, é, í, ó, ú, ñ, etc...

<img width="613" alt="Screenshot 2019-10-17 at 16 33 40" src="https://user-images.githubusercontent.com/11478307/67018720-e7ec6e80-f0fb-11e9-8e09-98b0205626fb.png">

[caixa-one-page-spanish.pdf](https://github.com/axa-group/Parsr/files/3739812/caixa-one-page-spanish.pdf)

**Comment by peter-vandenabeele-axa** [comment]
Sorry, I fail to understand the title, relative to the problem statement.

I understand this as "pdfminer can't parse characters outside the ASCII encoding"
(because the "accent" characters from French and Spanish etc. that you refer to _are_ part of utf-8).

Probably I am just misunderstanding ?

**Comment by aarohijohal** [comment]
It's actually more complicated than that.
Also: this behavior can also manifest on standard latin characters: it all depends on how the PDF document was encoded - a PDF _can_ lack a complete textual mapping by omission since it is not an inherent purpose of the PDF format to provide the textual equivalent.

Related Issues:
1. https://github.com/axa-group/Parsr/issues/75
2. https://github.com/aarohijohal/pdfminer.six/issues/1
3. https://github.com/pdfminer/pdfminer.six/issues/130

**Comment by aarohijohal** [comment]
> Attached is a document in spanish that shows that pdfminer cant process latin characters like:
> á, é, í, ó, ú, ñ, etc...

It's actually more complicated than that.
Also: this behavior can also manifest on standard latin characters: it all depends on how the PDF document was encoded - a PDF can lack a complete textual mapping by omission since it is not an inherent purpose of the PDF format to provide the textual equivalent.

Related Issues:

1.    #75
2.    aarohijohal/pdfminer.six#1
3.    pdfminer/pdfminer.six#130

**Comment by aarohijohal** [comment]
An interesting related patent: https://patents.google.com/patent/US20060288281

**Comment by aarohijohal** [comment]
This is a general problem related to the extractors used, instead of being particularly Parsr's problem.
