### ISSUE TITLE
Use ghostscript instead of convert to generate intermediate TIFF files (from PDF) before extracting using tesseract

### ISSUE THREAD

**Issue by aarohijohal** [axa-group/Parsr#20]
Currently with some specific documents, the PDF pre processing step (a call to convert that generates tiff files) can generate low resolution images. Theses images are then passed to tesseract and the results are quite bad.

We should make sure that:

- the target images are big enough to get good results from tesseract.
- the processing time is fast enough.

We had a look at calling ghostscript directly.
300 dpi seems well enough and Ghostscript is faster than Convert.

```
$ gs -dNOPAUSE -q -sDEVICE=tiff48nc -dBATCH -sOutputFile=a.tiff -r300 a.pdf -c quit
```

Note that this create some pretty huge files.

**Comment by jvalls-axa** [comment]
Converting PDFs to images is currently not performed because our image detection module allows to 'ocr' detected images in a PDF therefore we don't need to convert full PDF to images before run OCR.

Anyway when input file is an image we have an 'image optimisation' step before run 'ocr' that ensures that input file will be optimised (black & white conversion, shadows removal and rotation correction).
